{% set name = "od" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 180fb0d13c3af1384047b8296c95683816b5d0c68a60c22d07c703be8bd755cb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - od

about:
  home: https://github.com/epsy/od
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Shorthand syntax for building OrderedDicts
  dev_url: https://github.com/epsy/od

extra:
  recipe-maintainers:
    - proinsias
